### PR TITLE
Fix computed property overridability deprecation warnings

### PR DESCRIPTION
**Pull request by herzzanu**
Solves this https://deprecations.emberjs.com/v3.x/#toc_computed-property-override

### CODE REVIEW

**Comment by Exelord** [comment]
Hmm, does it mean all CP will readOnly by default? If yes, we need to apply more changes

**Comment by herzzanu** [comment]
Exactly. Well I tested it in production and this was the only deprecation warning I got.

**Comment by Exelord** [comment]
Probably we not override anything else, but it should be possible if there is no readOnly marker.
I will gonna apply this pattern for all :) Thanks for this contribution!

**Comment by herzzanu** [comment]
Ok, makes sense. Cool, you're welcome :)

**Pull request merged**
