### PR TITLE
update engines package.json

### LINKED ISSUE #60: Node.js Version Issues
the `engines` configuration doesn't allow node > 6

### PR DESCRIPTION
**Pull request by donaldwasserman**
Fixes #60

### CODE REVIEW

**Comment by Exelord** [comment]
You are right! my bad sorry!

**Comment by Exelord** [comment]
Thank you for the contribution!

**Comment by donaldwasserman** [comment]
Just a helpful reminder, @Exelord you forgot to actually merge this 😄 

Happy to help (also, I need to this addon).

**Comment by Exelord** [comment]
The tests were running actually when I was reviewing it ;)

**Pull request merged**
